#### Tensor

`torch.Tensor`

If you set attribute of torch.Tensor `.requires_grad` as `True`, it starts to track all operations on it.

To stop a tensor from tracking history, you can call `detach()` to detach it from the computation history.

In [1]:
import torch


x = torch.ones(2, 3, requires_grad = True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [2]:
y = x + 2
print(y)

tensor([[3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward>)


In [3]:
print(y.grad_fn)

`y` was created as a result of an operation, so it has a `grad_fn`

Do more operation on `Y`

In [6]:
z = y*y*4

In [8]:
out = z.mean()
print(z, out)

tensor([[36., 36., 36.],
        [36., 36., 36.]], grad_fn=<MulBackward>) tensor(36., grad_fn=<MeanBackward1>)


#### Gradients

Let's backprop now Because `out` contains a single scalar, `out.backward()` is equivalent to `out.backward(torch.tensor(1))`

In [9]:
out.backward()

In [10]:
print(x.grad)

tensor([[4., 4., 4.],
        [4., 4., 4.]])
