In [2]:
import torch

x = torch.empty(5, 3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5662, 0.1320, 0.3753],
        [0.5845, 0.2922, 0.8836],
        [0.2084, 0.2788, 0.8755],
        [0.2165, 0.6433, 0.2628],
        [0.1845, 0.0790, 0.3027]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)

In [7]:
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.tensor([5, 4])
print(x)

tensor([5, 4])


In [9]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [10]:
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0.8500, 0.7811, 0.0689],
        [0.4180, 0.9347, 0.2074],
        [0.4021, 0.3290, 0.7061],
        [0.8913, 0.2743, 0.1704],
        [0.9505, 0.6318, 0.8499]])


In [15]:
print(x.shape)

torch.Size([5, 3])


In [17]:
# another way to get size of torch tensor
print(x.size())

torch.Size([5, 3])


### Operations

In [18]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.6644, 0.9293, 0.6395],
        [1.1362, 1.2407, 0.2619],
        [1.1047, 1.1651, 1.0800],
        [0.9216, 0.6622, 0.8506],
        [1.4115, 0.7750, 1.5413]])


In [19]:
z = torch.add(x, y)
print(z)

tensor([[1.6644, 0.9293, 0.6395],
        [1.1362, 1.2407, 0.2619],
        [1.1047, 1.1651, 1.0800],
        [0.9216, 0.6622, 0.8506],
        [1.4115, 0.7750, 1.5413]])


In [20]:
y.add_(x)
print(y)

tensor([[1.6644, 0.9293, 0.6395],
        [1.1362, 1.2407, 0.2619],
        [1.1047, 1.1651, 1.0800],
        [0.9216, 0.6622, 0.8506],
        [1.4115, 0.7750, 1.5413]])


In [21]:
print(x[:, 1])

tensor([0.7811, 0.9347, 0.3290, 0.2743, 0.6318])


Resizing: if you want to resize/reshape tensor, you can use `torch.view`

In [23]:
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### NumPy bridge

Converting a Torch tensor to a NumPy array

In [25]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [27]:
a.add_(2)
print(a, b)

tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


Converting a NumPy array to a torch tensor

In [28]:
import numpy as np
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [29]:
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors

In [33]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
else:
    print('run without cuda ...')
    print(z.to('cpu', torch.double))

run without cuda ...
tensor([[0.5323, 0.1750, 0.1211, 0.8385, 0.7478, 0.3590, 0.5480, 0.2584],
        [0.1285, 0.4920, 0.1420, 0.4312, 0.6578, 0.5882, 0.8063, 0.4935]],
       dtype=torch.float64)
